#dummy, siden ai ikke funker enda
# scripts/run_agents.py
from pathlib import Path
import json
import pandas as pd

from agents import system_prompt, user_prompt
from schema import validate_prediction

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = REPO_ROOT / "outputs" / "dataset_with_notes.csv"
OUT_PATH = REPO_ROOT / "outputs" / "predictions.jsonl"

PANELS = ["sofie", "dorte"]
ROLES = ["gp", "radiology"]


# bytter ut med call_openai(...) eller call_hf_model(...) når vi har fått tilgang
def dummy_model(note_text: str, case_id: str, role: str, panel: str, label: int):
    """
    Brukes når du ikke har tilgang på LLM.
    Returnerer et gyldig JSON-objekt i korrekt schema.
    """
    # super-enkel baseline: litt høyere prob ved label=1 (bare for å ha noe)
    base_p = 0.65 if label == 1 else 0.35

    if panel == "sofie":
        p_yes = max(0.05, base_p - 0.10)  # mer konservativ
    else:
        p_yes = min(0.95, base_p + 0.10)  # mer risk-averse

    decision = "YES" if p_yes >= 0.5 else "NO"

    return {
        "case_ID": str(case_id),
        "role": role,
        "panel": panel,
        "label": int(label),
        "Decision": decision,
        "Probability_yes": float(round(p_yes, 2)),
        "self_confidence": 0.55,
        "rationale_bullets": [
            "This is a placeholder output because LLM access is not available.",
            "Decision is generated by a simple baseline rule for pipeline testing.",
            "Replace dummy_model with GPT/Qwen/MedGemma when access is granted."
        ],
        "evidence_cited": ["Case ID", "label (for baseline only)"]
    }

def run():
    df = pd.read_csv(DATA_PATH)

    # sanity
    required_cols = ["patient_ID", "label", "input_text_gp", "input_text_radiology"]
    for c in required_cols:
        if c not in df.columns:
            raise ValueError(f"Missing column in dataset: {c}")

    OUT_PATH.parent.mkdir(exist_ok=True)

    n_written = 0
    with OUT_PATH.open("w", encoding="utf-8") as f:
        for _, row in df.iterrows():
            case_id = row["patient_ID"]
            label = row["label"]

            for panel in PANELS:
                # GP
                obj_gp = dummy_model(
                    note_text=row["input_text_gp"],
                    case_id=case_id,
                    role="gp",
                    panel=panel,
                    label=label
                )
                validate_prediction(obj_gp)
                f.write(json.dumps(obj_gp, ensure_ascii=False) + "\n")
                n_written += 1

                # Radiology
                obj_rad = dummy_model(
                    note_text=row["input_text_radiology"],
                    case_id=case_id,
                    role="radiology",
                    panel=panel,
                    label=label
                )
                validate_prediction(obj_rad)
                f.write(json.dumps(obj_rad, ensure_ascii=False) + "\n")
                n_written += 1

    print("Saved:", OUT_PATH)
    print("Rows written:", n_written)

if __name__ == "__main__":
    run()

